name: Update Slippi Rankings

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:       # Manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'  # Use LTS or match your local env

    - name: Install project dependencies
      run: yarn install

    - name: Prepare data folder
      run: |
        mkdir -p cron/data
        [ -f cron/data/players-new.json ] || echo '[]' > cron/data/players-new.json

    - name: Fetch stats and deploy to GitHub Pages
      env:
        NODE_OPTIONS: --openssl-legacy-provider
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
      run: |
        yarn ts-node cron/fetchStats.ts
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        yarn run deploy -- -u "github-actions-bot <support+actions@github.com>"

    - name: Upload updated player data (artifact)
      uses: actions/upload-artifact@v4
      with:
        name: player-data
        path: cron/data/players-new.json
        overwrite: true
