name: Update slippi rankings

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18.12.0'  # Use a stable Node.js version
    - name: Install Yarn
      run: npm install -g yarn
    - name: Install project dependencies
      run: yarn install
    - name: Load secrets
      run: |
        mkdir -p ./secrets
        cat << EOF > ./secrets/creds.json
        ${{ secrets.GOOGLE_CREDS }}
        EOF
      shell: bash
    - uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: player-data
        path: cron/data/players-new.json
    - name: Load latest player data and deploy to GitHub Pages
      run: |
        git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        ./cron/run.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v4
      with:
        name: player-data
        path: cron/data/players-new.json
        overwrite: true
